GET http://localhost:7000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBcnpha3kgTXVoIiwiZW1haWwiOiJ6YWt5QGdtYWlsLmNvbSIsImlhdCI6MTY4ODM2NTU2NSwiZXhwIjoxNjg4MzY1NTgwfQ.6ljPTIUOKzVr1tVqIC55dAJtGG-8-u6gxZuG_N9pkmw
###
POST http://localhost:7000/users
Content-Type: application/json

{
    "name": "Arzaky Muh",
    "email": "zaky@gmail.com",
    "password": "123123", 
    "confpassword": "123123"
}

###
POST http://localhost:7000/login
Content-Type: application/json

{
    # "email": "zaky@gmail.com",
    "name": "Arzaky Muh",
    "password": "123123"
}

###
GET http://localhost:7000/token

### 
DELETE http://localhost:7000/logout

